//console.warn("Crystal Has Loaded")

import { world, system, EntityInventoryComponent, ItemStack, ItemUseOnBeforeEvent } from "@minecraft/server"
import { ActionFormData, ModalFormData } from "@minecraft/server-ui"


world.beforeEvents.itemUse.subscribe(data => {
    let player = data.source
    
    if (data.itemStack.typeId == "gui:quartz_crystal") system.run(() => main(player))}
)

function main(player){
    //console.warn("event handler works")
    let currentLevel = player.level
    //player.runCommandAsync('')
    console.warn(currentLevel)
    let iscrounch = player.isSneaking
    console.warn(iscrounch)

    if(iscrounch === true){
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
        player.runCommandAsync('summon xp_orb ~ ~ ~')
    }
    else
    {
        //who ever gets the item edit this command to the location that they want
        console.warn("The Tp Point can be swaped at any point")
        player.runCommandAsync('tp @s -499 80 190')
    }
    

}